// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCemKQO2l-SCqURBJsGpiTTZDjrjarOTvE',
    appId: '1:926953805411:web:27e946eca45cfc5a21ca56',
    messagingSenderId: '926953805411',
    projectId: 'student-job-app-1d837',
    authDomain: 'student-job-app-1d837.firebaseapp.com',
    storageBucket: 'student-job-app-1d837.firebasestorage.app',
    measurementId: 'G-1T32NKY0BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnBMVBONwiGkUsDMNv0vSy6hp6Tp7Xdvk',
    appId: '1:926953805411:android:b67167446b7311f621ca56',
    messagingSenderId: '926953805411',
    projectId: 'student-job-app-1d837',
    storageBucket: 'student-job-app-1d837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq5VhRlgAiZxCNVidnXcufqJC1EVJaLGA',
    appId: '1:926953805411:ios:5696d06e78cb49b621ca56',
    messagingSenderId: '926953805411',
    projectId: 'student-job-app-1d837',
    storageBucket: 'student-job-app-1d837.firebasestorage.app',
    iosBundleId: 'com.example.studentJobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq5VhRlgAiZxCNVidnXcufqJC1EVJaLGA',
    appId: '1:926953805411:ios:5696d06e78cb49b621ca56',
    messagingSenderId: '926953805411',
    projectId: 'student-job-app-1d837',
    storageBucket: 'student-job-app-1d837.firebasestorage.app',
    iosBundleId: 'com.example.studentJobApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCemKQO2l-SCqURBJsGpiTTZDjrjarOTvE',
    appId: '1:926953805411:web:8e837be194d41c1321ca56',
    messagingSenderId: '926953805411',
    projectId: 'student-job-app-1d837',
    authDomain: 'student-job-app-1d837.firebaseapp.com',
    storageBucket: 'student-job-app-1d837.firebasestorage.app',
    measurementId: 'G-YT42XDQ375',
  );
}
